image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64
# https://git.beagleboard.org/beagleboard/ci-docker-images

#before_script:
#  - apt-get update -q && apt-get install -y -q device-tree-compiler

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - mirror/x86_64-gcc-*-linux.tar.xz
    - ccache.tar.gz

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - git config --global user.email "Beagle@BeagleBoard.org"
    - git config --global user.name "Beagle User"
    - touch .gitlab-runner
    - mkdir -p /root/.cache/ccache/ || true
    - ccache -s
    - tar -xf ccache.tar.gz -C / || true
    - ccache -s
    - ./01_git_sync.sh
    - ./02_build_opensbi.sh
    - ./03_build_uboot.sh
    - ./04_build_linux.sh
    - ./05_generate_boot.sh
    - ./06_generate_debian_console_root.sh
    - xz -vT8 deploy/boot.ext4
    - xz -vT8 deploy/root.ext4
    - ccache -s
    - tar -cf ccache.tar.gz /root/.cache/ccache/
  artifacts:
    when: on_success
    expire_in: 28 days
    name: "$CI_PROJECT_NAME-mainline-$CI_JOB_ID"
    paths:
      - "deploy/fastboot_emmc.sh"
      - "deploy/mac_fastboot_emmc.sh"
      - "deploy/u-boot-with-spl.bin"
      - "deploy/boot.ext4.xz"
      - "deploy/root.ext4.xz"
